# Use this when testing new windows commands for the one-liner script
name: Windows Split Commands
on:
  push:
    branches:
      - 'win-test*'
jobs:
  Windows-Step-by-Step:
    runs-on: [windows-2019, windows-2022]
    steps:
      - name: 👉🏽 Update Execution Policy
        run: |
          $Policy = Get-ExecutionPolicy -Scope Process;
          echo "Policy was $Policy"
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          $Policy = Get-ExecutionPolicy -Scope Process;
          echo "Policy is now $Policy"
      - name: 👉🏽 Update SecurityProtocol
        run: |
          $Protocol = [System.Net.ServicePointManager]::SecurityProtocol
          echo "Protocol was $Protocol"
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          $Protocol = [System.Net.ServicePointManager]::SecurityProtocol
          echo "Protocol is now $Protocol"
      - name: 👉🏽 Download script
        run: |
          iwr -Uri "https://raw.githubusercontent.com/edgeimpulse/ei-install-scripts/${{ github.ref_name }}/install-windows.ps1" -Outfile install.ps1;
          dir;
      - name: 👉🏽 Execute script
        run: |
          iex .\install.ps1;
          dir;
      - name: 👉🏽 Delete script
        run: |
          del .\install.ps1;
          dir;
      - name: 👉🏽 Test edge-impulse-cli
        run: |
          edge-impulse-uploader --api-key notarealkey --category training path/to/file.wav;
          edge-impulse-daemon --version;
